version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: "curl http://localhost:9200/_cat/health"
      interval: 1s
      timeout: 30s
      retries: 300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ES_HEAP_SIZE: "2g"
      discovery.type: single-node
      xpack.security.enabled: "false"
    networks:
      - elk
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  elk:
    driver: bridge
volumes:
  elasticsearch:
